services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  prefect-server:
    image: prefecthq/prefect:2-latest
    container_name: prefect-server
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"

  prefect-worker:
    image: prefecthq/prefect:2-latest
    container_name: prefect-worker
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    command: prefect worker start --pool default-agent-pool