# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpEqnEQ0vFjxbvAXPWfnCWiKoBy0tYzo
"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# 1. Generate Moon dataset
X, y = make_moons(n_samples=1000, noise=0.25, random_state=42)

# 2. Train/Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 3. Build Polynomial + Logistic Regression model
model = Pipeline([
    ("scaler", StandardScaler()),
    ("poly", PolynomialFeatures(degree=5)),  # try 2,3,5
    ("logreg", LogisticRegression())
])

# 4. Train model
model.fit(X_train, y_train)

# 5. Predictions
y_pred = model.predict(X_test)

# 6. Accuracy
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

# 7. Decision boundary visualization
xx, yy = np.meshgrid(
    np.linspace(X[:,0].min()-1, X[:,0].max()+1, 200),
    np.linspace(X[:,1].min()-1, X[:,1].max()+1, 200)
)

Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

plt.figure(figsize=(8,6))
plt.contourf(xx, yy, Z, alpha=0.3)

plt.scatter(X[:,0], X[:,1], c=y, edgecolor="k")
plt.title("Polynomial Model on Moon Dataset")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

X, y = make_moons(n_samples=500, noise=0.25, random_state=42)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

linear_model = LogisticRegression()
linear_model.fit(X_train, y_train)

degrees = [1, 2, 5]
models = {}

for degree in degrees:
    model = Pipeline([
        ("poly", PolynomialFeatures(degree=degree)),
        ("logreg", LogisticRegression())
    ])

    model.fit(X_train, y_train)
    models[degree] = model


def plot_boundary(model, title):
    x_min, x_max = X[:,0].min()-1, X[:,0].max()+1
    y_min, y_max = X[:,1].min()-1, X[:,1].max()+1

    xx, yy = np.meshgrid(
        np.linspace(x_min, x_max, 200),
        np.linspace(y_min, y_max, 200)
    )

    Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    plt.contourf(xx, yy, Z, alpha=0.3)
    plt.scatter(X[:,0], X[:,1], c=y, edgecolor='k')
    plt.title(title)
    plt.show()

plot_boundary(linear_model, "Linear Model (Moon Dataset)")


for degree, model in models.items():
    plot_boundary(model, f"Polynomial Degree {degree} (Moon Dataset)")

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# 1. Generate dataset
X, y = make_moons(n_samples=500, noise=0.25, random_state=42)

# 2. Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 3. Train Linear Regression
model = LinearRegression()
model.fit(X_train, y_train)

# 4. Create grid for visualization
x_min, x_max = X[:,0].min() - 1, X[:,0].max() + 1
y_min, y_max = X[:,1].min() - 1, X[:,1].max() + 1

xx, yy = np.meshgrid(
    np.linspace(x_min, x_max, 200),
    np.linspace(y_min, y_max, 200)
)

grid = np.c_[xx.ravel(), yy.ravel()]
Z = model.predict(grid)
Z = Z.reshape(xx.shape)

# 5. Plot
plt.figure(figsize=(8,6))
plt.contourf(xx, yy, Z, cmap="coolwarm", alpha=0.4)
plt.scatter(X[:,0], X[:,1], c=y, edgecolor='k')

plt.title("Linear Regression on Moon Dataset")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

import pandas as pd
import numpy as np
import io

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_squared_error

# =========================================================
# 1. خيار اختيار ورفع الملف من جهازك
# =========================================================
print("الرجاء اختيار ملف data.csv من جهازك:")
uploaded = files.upload()

# قراءة الملف المرفوع مباشرة من الذاكرة
file_name = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

# تصفية البيانات من القيم الصفرية (البيانات غير المسعرة)
df = df[df["price"] > 0]

# تحويل السعر بالآلاف
df["price"] = df["price"] / 1000

# =========================================================
# 2. إزالة القيم الشاذة (IQR METHOD)
# =========================================================
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[(df["price"] >= lower_bound) & (df["price"] <= upper_bound)]
print("\nحجم البيانات بعد التنظيف وإزالة القيم الشاذة:", df.shape)

# =========================================================
# 3. تحديد الميزات المستهدفة (Feature Selection)
# =========================================================
y = df["price"]

# حذف الأعمدة المتكررة والمتداخلة لتفادي Multi-Collinearity
X = df.drop(columns=["price", "date", "street", "sqft_living", "city", "country"])

numeric_features = [
    "bedrooms", "bathrooms", "sqft_lot", "floors",
    "waterfront", "view", "condition",
    "sqft_above", "sqft_basement",
    "yr_built", "yr_renovated"
]

categorical_features = ["statezip"]

# =========================================================
# 4. معالجة البيانات مسبقاً (Preprocessing)
# =========================================================
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(drop="first", handle_unknown="ignore"), categorical_features)
    ]
)

# =========================================================
# 5. بناء خط الأنابيب (Pipeline)
# =========================================================
model = Pipeline(
    steps=[
        ("prep", preprocessor),
        ("reg", LinearRegression())
    ]
)

# =========================================================
# 6. تقسيم البيانات (Train / Test Split)
# =========================================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

# =========================================================
# 7. تدريب النموذج (Train)
# =========================================================
model.fit(X_train, y_train)

# =========================================================
# 8. تقييم النموذج (Evaluate)
# =========================================================
y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("\nMODEL PERFORMANCE")
print("--------------------")
print("R² Score:", round(r2, 4))
print("RMSE:", round(rmse, 2), "($ thousands)")

# =========================================================
# 9. المعاملات الأكثر تأثيراً (Reliable Coefficients)
# =========================================================
num_features = numeric_features
cat_features = model.named_steps["prep"] \
    .named_transformers_["cat"] \
    .get_feature_names_out(categorical_features)

feature_names = list(num_features) + list(cat_features)
coefficients = model.named_steps["reg"].coef_

coef_table = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coefficients
})

coef_table["Abs_Effect"] = coef_table["Coefficient"].abs()
coef_table = coef_table.sort_values("Abs_Effect", ascending=False)

print("\nTOP RELIABLE COEFFICIENTS")
print("-------------------------")
print(coef_table[["Feature", "Coefficient"]].head(20))

# =========================================================
# 10. عينة من التوقعات (Sample Predictions)
# =========================================================
comparison = pd.DataFrame({
    "Actual_Price_(Thousands)": y_test.values,
    "Predicted_Price_(Thousands)": y_pred
})

print("\nSAMPLE PREDICTIONS")
print("--------------------")
print(comparison.head(10))

import pandas as pd
import numpy as np
import io

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_squared_error

# =========================================================
# 1. خيار اختيار ورفع الملف من جهازك
# =========================================================
print("الرجاء اختيار ملف data.csv من جهازك:")
uploaded = files.upload()

# قراءة الملف المرفوع
file_name = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

# تصفية البيانات من القيم الصفرية والأخطاء
df = df[df["price"] > 0]

# تحويل السعر بالآلاف
df["price"] = df["price"] / 1000

# =========================================================
# 2. إزالة القيم الشاذة (IQR METHOD)
# =========================================================
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[(df["price"] >= lower_bound) & (df["price"] <= upper_bound)]
print("\nحجم البيانات بعد التنظيف وإزالة القيم الشاذة:", df.shape)

# =========================================================
# 3. تحديد الميزات (Feature Selection)
# =========================================================
y = df["price"]

# استبعاد الأعمدة المتكررة وغير المفيدة
X = df.drop(columns=["price", "date", "street", "sqft_living", "city", "country"])

numeric_features = [
    "bedrooms", "bathrooms", "sqft_lot", "floors",
    "waterfront", "view", "condition",
    "sqft_above", "sqft_basement",
    "yr_built", "yr_renovated"
]

categorical_features = ["statezip"]

# =========================================================
# 4. معالجة البيانات مسبقاً (Preprocessing)
# =========================================================
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(drop="first", handle_unknown="ignore"), categorical_features)
    ]
)

# =========================================================
# 5. بناء خط الأنابيب مع إضافة Polynomial Features
# =========================================================
# تم إضافة PolynomialFeatures للميزات الرقمية فقط لتفادي تضخم الأعمدة الفئوية (Zip codes)
model = Pipeline(
    steps=[
        ("prep", preprocessor),
        ("poly", PolynomialFeatures(degree=2, include_bias=False)), # تحويل العلاقات إلى علاقات متعددة الحدود
        ("reg", LinearRegression())
    ]
)

# =========================================================
# 6. تقسيم البيانات (Train / Test Split)
# =========================================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

# =========================================================
# 7. تدريب النموذج (Train)
# =========================================================
model.fit(X_train, y_train)

# =========================================================
# 8. تقييم النموذج (Evaluate)
# =========================================================
y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("\nMODEL PERFORMANCE (POLYNOMIAL REGRESSION)")
print("------------------------------------------")
print("R² Score:", round(r2, 4))
print("RMSE:", round(rmse, 2), "($ thousands)")

# =========================================================
# 9. عينة من التوقعات (Sample Predictions)
# =========================================================
comparison = pd.DataFrame({
    "Actual_Price_(Thousands)": y_test.values,
    "Predicted_Price_(Thousands)": y_pred
})

print("\nSAMPLE PREDICTIONS")
print("--------------------")
print(comparison.head(10))

import pandas as pd
import numpy as np
import io

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_squared_error

print("الرجاء اختيار ملف data.csv من جهازك:")
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

df = df[df["price"] > 0]
df["price"] = df["price"] / 1000

Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[(df["price"] >= lower_bound) & (df["price"] <= upper_bound)]
print("\nحجم البيانات بعد التنظيف وإزالة القيم الشاذة:", df.shape)

y = df["price"]
X = df.drop(columns=["price", "date", "street", "sqft_living", "city", "country"])

numeric_features = [
    "bedrooms", "bathrooms", "sqft_lot", "floors",
    "waterfront", "view", "condition",
    "sqft_above", "sqft_basement",
    "yr_built", "yr_renovated"
]

categorical_features = ["statezip"]

numeric_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("poly", PolynomialFeatures(degree=2, include_bias=False))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", OneHotEncoder(drop="first", handle_unknown="ignore"), categorical_features)
    ]
)

model = Pipeline(
    steps=[
        ("prep", preprocessor),
        ("reg", LinearRegression())
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("\nMODEL PERFORMANCE (CORRECT POLYNOMIAL PIPELINE)")
print("------------------------------------------")
print("R² Score:", round(r2, 4))
print("RMSE:", round(rmse, 2), "($ thousands)")

comparison = pd.DataFrame({
    "Actual_Price_(Thousands)": y_test.values,
    "Predicted_Price_(Thousands)": y_pred
})

print("\nSAMPLE PREDICTIONS")
print("--------------------")
print(comparison.head(10))

import pandas as pd
import numpy as np
import io

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_squared_error

print("Please select the data.csv file from your device:")
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

df = df[df["price"] > 0]
df["price"] = df["price"] / 1000

Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[(df["price"] >= lower_bound) & (df["price"] <= upper_bound)]
print("\nData shape after cleaning and outlier removal:", df.shape)

y = df["price"]
X = df.drop(columns=["price", "date", "street", "sqft_living", "city", "country"])

numeric_features = [
    "bedrooms", "bathrooms", "sqft_lot", "floors",
    "waterfront", "view", "condition",
    "sqft_above", "sqft_basement",
    "yr_built", "yr_renovated"
]

categorical_features = ["statezip"]

numeric_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("poly", PolynomialFeatures(degree=2, include_bias=False))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", OneHotEncoder(drop="first", handle_unknown="ignore"), categorical_features)
    ]
)

model = Pipeline(
    steps=[
        ("prep", preprocessor),
        ("reg", LinearRegression())
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("\nMODEL PERFORMANCE (CORRECT POLYNOMIAL PIPELINE)")
print("------------------------------------------")
print("R² Score:", round(r2, 4))
print("RMSE:", round(rmse, 2), "($ thousands)")

comparison = pd.DataFrame({
    "Actual_Price_(Thousands)": y_test.values,
    "Predicted_Price_(Thousands)": y_pred
})

print("\nSAMPLE PREDICTIONS")
print("--------------------")
print(comparison.head(10))

import pandas as pd
import numpy as np
import io

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_squared_error

print("Please select the data.csv file from your device:")
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

df = df[df["price"] > 0]
df["price"] = df["price"] / 1000

Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df = df[(df["price"] >= lower_bound) & (df["price"] <= upper_bound)]

# --- Feature Engineering ---
df["house_age"] = 2014 - df["yr_built"]
df["is_renovated"] = (df["yr_renovated"] > 0).astype(int)

print("\nData shape after cleaning and feature engineering:", df.shape)

# Log transformation of the target variable to boost performance
y = np.log1p(df["price"])
X = df.drop(columns=["price", "date", "street", "sqft_living", "city", "country", "yr_built", "yr_renovated"])

numeric_features = [
    "bedrooms", "bathrooms", "sqft_lot", "floors",
    "waterfront", "view", "condition",
    "sqft_above", "sqft_basement",
    "house_age", "is_renovated"
]

categorical_features = ["statezip"]

numeric_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("poly", PolynomialFeatures(degree=2, include_bias=False))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", OneHotEncoder(drop="first", handle_unknown="ignore"), categorical_features)
    ]
)

model = Pipeline(
    steps=[
        ("prep", preprocessor),
        ("reg", LinearRegression())
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

model.fit(X_train, y_train)

y_pred_log = model.predict(X_test)

# Convert predictions back from log scale to thousands of dollars
y_test_actual = np.expm1(y_test)
y_pred_actual = np.expm1(y_pred_log)

r2 = r2_score(y_test_actual, y_pred_actual)
rmse = np.sqrt(mean_squared_error(y_test_actual, y_pred_actual))

print("\nMODEL PERFORMANCE (OPTIMIZED POLYNOMIAL PIPELINE)")
print("-------------------------------------------------")
print("R² Score:", round(r2, 4))
print("RMSE:", round(rmse, 2), "($ thousands)")

comparison = pd.DataFrame({
    "Actual_Price_(Thousands)": y_test_actual.values,
    "Predicted_Price_(Thousands)": y_pred_actual
})

print("\nSAMPLE PREDICTIONS")
print("--------------------")
print(comparison.head(10))

import pandas as pd
import numpy as np
import io

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_squared_error

print("Please select the data.csv file from your device:")
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

df = df[df["price"] > 0]
df["price"] = df["price"] / 1000

Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df = df[(df["price"] >= lower_bound) & (df["price"] <= upper_bound)]

df["house_age"] = 2014 - df["yr_built"]
df["is_renovated"] = (df["yr_renovated"] > 0).astype(int)

print("\nData shape after cleaning and feature engineering:", df.shape)

y = np.log1p(df["price"])
X = df.drop(columns=["price", "date", "street", "sqft_living", "city", "country", "yr_built", "yr_renovated"])

numeric_features = [
    "bedrooms", "bathrooms", "sqft_lot", "floors",
    "waterfront", "view", "condition",
    "sqft_above", "sqft_basement",
    "house_age", "is_renovated"
]

categorical_features = ["statezip"]

numeric_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("poly", PolynomialFeatures(degree=2, include_bias=False))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", OneHotEncoder(drop="first", handle_unknown="ignore"), categorical_features)
    ]
)

model = Pipeline(
    steps=[
        ("prep", preprocessor),
        ("reg", LinearRegression())
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

model.fit(X_train, y_train)

y_pred_log = model.predict(X_test)

y_test_actual = np.expm1(y_test)
y_pred_actual = np.expm1(y_pred_log)

r2 = r2_score(y_test_actual, y_pred_actual)
rmse = np.sqrt(mean_squared_error(y_test_actual, y_pred_actual))

print("\nMODEL PERFORMANCE (MAX OPTIMIZED PIPELINE)")
print("-------------------------------------------------")
print("R² Score:", round(r2, 4))
print("RMSE:", round(rmse, 2), "($ thousands)")

comparison = pd.DataFrame({
    "Actual_Price_(Thousands)": y_test_actual.values,
    "Predicted_Price_(Thousands)": y_pred_actual
})

print("\nSAMPLE PREDICTIONS")
print("--------------------")
print(comparison.head(10))